name: 'Setup Action'
description: 'Setup an OpenSAFELY environment'

inputs:
  cache:
    description: 'If dependencies should be cached, use this parameter to specify the package manager. Supported values: pip, pipenv, poetry. Set to null to disable dependency caching'
    required: false
    default: 'pip'
  cache-dependency-path:
    description: 'The path to dependency files whose dependencies should be cached.'
    required: false
    default: 'requirements.*.txt'
  python-version:
    description: 'The Python version to use. A value is required in order to install Python'
    required: false
  install-just:
    description: 'If true, this installs Just'
    required: false

runs:
  using: 'composite'

  steps:
    - uses: "actions/setup-python@v5"
      if: ${{ inputs.python-version }}
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    - name: Install just
      if: ${{ inputs.install-just }}
      shell: bash
      run: |
        mkdir -p "$HOME/bin"
        bash "${{ github.action_path }}"/install-just.sh --to "$HOME/bin" --tag 1.34.0
        echo "$HOME/bin" >> $GITHUB_PATH
