name: 'Setup Action'
description: 'Setup an OpenSAFELY environment'

inputs:
  python-version:
    description: 'The Python version to use. A value is required in order to install Python'
    required: false
  install-just:
    description: 'If true, this installs Just'
    required: false

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: "actions/setup-python@v4"
      if: ${{ inputs.python-version }}
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: requirements.*.txt
    - name: Install just
      if: ${{ inputs.install-just }}
      run: |
        curl -L https://github.com/casey/just/releases/download/1.9.0/just-1.9.0-x86_64-unknown-linux-musl.tar.gz \
         | tar -xzf - --directory /usr/local/bin just
      shell: bash