name: 'Setup Action'
description: 'Setup an OpenSAFELY environment'

inputs:
  cache-dependency-path:
    description: 'The path to dependency files whose dependencies should be cached.'
    required: false
    default: 'requirements.*.txt'
  python-version:
    description: 'The Python version to use. A value is required in order to install Python'
    required: false
  install-just:
    description: 'If true, this installs Just'
    required: false

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: "actions/setup-python@v4"
      if: ${{ inputs.python-version }}
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    - name: Install just
      if: ${{ inputs.install-just }}
      shell: bash
      run: |
        mkdir -p "$HOME/bin"
        bash install-just.sh --to "$HOME/bin" --tag 1.11.0
        echo "$HOME/bin" >> $GITHUB_PATH
