name: self test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    env:
      JUST_VERSION: 1.34.0
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
          - windows-2025
          - macOS-14
          - macOS-13
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: self test
        uses: ./
        with:
          python-version: "3.10"
          install-just: true
      - name: test just works
        shell: bash
        run: |
          just --version
          just --version | grep -q "$JUST_VERSION"
      - name: test python3.10 works and has installed requests
        shell: bash
        run: python -m pip install -r requirements.test.txt
